version: '3.1'

services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - /path/to/local/directory:/var/lib/postgresql/data
        networks:
            - db_network

volumes:
    db_data:

networks:
    db_network: