services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234  # Updated password
      POSTGRES_DB: postgres  # Updated database name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    networks:
      - db_network

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    networks:
      - db_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  db_network: